icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "custom"
command = "$HOME/.config/i3status-rs/scripts/wifi/wifi_name"
interval = 5
[block.theme_overrides]
idle_bg = "#fff300"
idle_fg = "#000000"

[[block]]
block = "cpu"
[block.theme_overrides]
idle_bg = "#FF0000"
idle_fg = "#000000"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon / $available.eng(w:2) "
[[block.click]]
button = "left"
cmd = "kitty -e ranger" 
[block.theme_overrides]
idle_bg = "#C500FF"
idle_fg = "#000000"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[[block.click]]
button = "left"
cmd = "kitty -e htop"
[block.theme_overrides]
idle_bg = "#FF8B00"
idle_fg = "#000000"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#62F142"
idle_fg = "#000000"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:' %a %d/%m  %R') "
[block.theme_overrides]
idle_bg = "#00fbff"
idle_fg = "#000000"

[[block]]
block = "custom"
command = "$HOME/.config/i3status-rs/scripts/distro/getDistro"
interval = "once"
[block.theme_overrides]
idle_bg = "#00ff9e"
idle_fg = "#000000"

[[block]]
block = "custom"
command = "echo ''"
[[block.click]]
button = "left"
cmd = "poweroff"
[[block.click]]
button = "right"
cmd = "reboot"
[block.theme_overrides]
idle_bg = "#1B1B32"
idle_fg = "#FFFFFF"
